scripts:
  - name: Create .env file
    script: |
      echo "$ENV_FILE" > $FCI_BUILD_DIR/.env
      ls -la $FCI_BUILD_DIR/.env
      cat $FCI_BUILD_DIR/.env

  - name: Flutter build
    script: |
      flutter build ipa --release