workflows:
  ios-release:
    name: iOS Release
    environment:
      groups:
        - env_vars
    scripts:
      - name: Criar arquivo .env
        script: |
          echo "$ENV_FILE" > $CM_BUILD_DIR/.env
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build iOS
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa